export { NavBar } from './NavBar'
export { Logo } from './Logo'
export { Mail } from './social-network/Mail'
export { SocialNetwork } from './social-network/SocialNetwork'
export { BouncingIcon } from './BouncingIcon'